BOOTLOADER = my-install

PROGS += cycles_per_sec.c

# make a local copy of cstart so you can modify it.
# COMMON_SRC += 

# define this if you need to give the device for your pi
TTYUSB = 

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template
